server.port=8080
spring.application.name=donaciones-service
spring.threads.virtual.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diegobravo2711@gmail.com
spring.mail.password=tkxowbclocovcuaf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*

weather-api.api-key= c2e8af2b8a14403f84d210400260607
weather-api.base-url= https://api.weatherapi.com/v1